# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160903_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='references',
            field=models.TextField(),
        ),
    ]
