# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160904_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='releases',
            new_name='release',
        ),
    ]
