# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='post',
            name='releases',
            field=models.CharField(choices=[('FR', 'Juno'), ('SO', 'Kilo'), ('JR', 'Liberty'), ('SR', 'Mitaka')], default='SR', max_length=2),
        ),
    ]
