# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160904_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release',
            field=models.CharField(choices=[('1', 'Live'), ('2', 'Kilo'), ('3', 'Liberty')], default='1', max_length=2),
        ),
    ]
