# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20160904_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('version',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='release',
        ),
        migrations.AddField(
            model_name='post',
            name='releases',
            field=models.ManyToManyField(to='website.Release'),
        ),
    ]
