# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20160905_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='releases',
        ),
        migrations.RemoveField(
            model_name='release',
            name='version',
        ),
        migrations.AddField(
            model_name='release',
            name='releases',
            field=models.ManyToManyField(to='website.Post'),
        ),
    ]
