# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160905_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='release',
        ),
        migrations.AddField(
            model_name='post',
            name='releases',
            field=models.ManyToManyField(to='website.Release_Info'),
        ),
    ]
