# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20160905_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='releases',
        ),
        migrations.AddField(
            model_name='post',
            name='release',
            field=models.CharField(choices=[('JUNO', 'Juno'), ('KILO', 'Kilo'), ('LIBERTY', 'Liberty')], default='JUNO', max_length=9),
        ),
        migrations.DeleteModel(
            name='Release_Info',
        ),
    ]
