# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20160905_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release',
            field=models.CharField(choices=[(1, 'Juno'), (2, 'Kilo'), (3, 'Liberty')], default='1', max_length=9),
        ),
    ]
