# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20160905_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releases', models.ManyToManyField(to='website.Post')),
            ],
        ),
    ]
