# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_releases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='releases',
        ),
        migrations.AlterField(
            model_name='post',
            name='release',
            field=models.CharField(blank=True, max_length=100, verbose_name='Select rules for customer segmentation'),
        ),
        migrations.DeleteModel(
            name='Releases',
        ),
    ]
