# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20160905_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release',
            field=models.IntegerField(choices=[(1, 'Juno'), (2, 'Kilo'), (3, 'Liberty')]),
        ),
    ]
