# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20160905_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='release',
        ),
    ]
