# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20160905_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='release',
        ),
        migrations.DeleteModel(
            name='ReleaseParent',
        ),
        migrations.AddField(
            model_name='post',
            name='releases',
            field=models.ManyToManyField(related_name='release', to='website.Release'),
        ),
    ]
