# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20160905_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_group_type', models.IntegerField(choices=[(0, 'Juno'), (1, 'Kilo'), (2, 'Mitaka')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.AlterField(
            model_name='post',
            name='releases',
            field=models.ManyToManyField(to='website.ReleaseGroup'),
        ),
    ]
