# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20160905_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ReleaseGroup',
        ),
        migrations.AlterField(
            model_name='post',
            name='releases',
            field=models.ManyToManyField(blank=True, null=True, to='website.Release'),
        ),
    ]
