# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20160906_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_names', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='release',
            field=models.ManyToManyField(blank=True, to='website.Release'),
        ),
    ]
