# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20160906_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='release',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
    ]
